### ISSUE TITLE
Transfer to the Foreman namespace

### ISSUE THREAD

**Issue by ekohl** [theforeman/hammer-cli-foreman-leapp#5]
Can we move this to https://github.com/theforeman so we have central control? In addition to that add https://rubygems.org/profiles/theforeman to https://rubygems.org/gems/hammer_cli_foreman_leapp so we can also release?

**Comment by ekohl** [comment]
Once it's transferred I can set up Transifex for translations too.

**Comment by ekohl** [comment]
@stejskalleos bump

**Comment by stejskalleos** [comment]
I don't have permission for the transfer, I added you as maintainer.

**Comment by ekohl** [comment]
As maintainer I can't move. I've temporarily enabled repo creation in theforeman org so you should be able to move it now.

**Comment by stejskalleos** [comment]
Done

**Comment by ekohl** [comment]
Thanks! I've disabled repo creation again.

**Comment by ekohl** [comment]
Now that it's been migrated I've created a project in Transifex so we can translate.

Reflecting the migration in the plugin overview: https://github.com/theforeman/foreman-plugin-overview/pull/13
